using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProductService.Application.DTOs
{
    /// <summary>
    /// Data Transfer Object for Product
    /// 
    /// Why DTO?
    /// - Decouples API from domain model
    /// - Only exposes what client needs
    /// - Prevents accidental data leaks
    /// - Can be versioned separately
    /// 
    /// Example:
    /// Domain Product entity has: Password, InternalNotes, Cost
    /// ProductDto only has: Id, Name, Price, Stock
    /// Client never sees sensitive data
    /// </summary>
    public class ProductDto
    {
        /// <summary>
        /// Unique product identifier
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Product name
        /// </summary>
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Product description
        /// </summary>
        public string Description { get; set; } = string.Empty;

        /// <summary>
        /// Stock Keeping Unit (unique warehouse identifier)
        /// </summary>
        public string Sku { get; set; } = string.Empty;

        /// <summary>
        /// Selling price
        /// </summary>
        public decimal Price { get; set; }

        /// <summary>
        /// Cost price (only for admin)
        /// </summary>
        public decimal Cost { get; set; }

        /// <summary>
        /// Total stock in warehouse
        /// </summary>
        public int StockQuantity { get; set; }

        /// <summary>
        /// Available quantity (can be purchased)
        /// = StockQuantity - ReservedQuantity
        /// </summary>
        public int AvailableQuantity { get; set; }

        /// <summary>
        /// Quantity reserved for pending orders
        /// </summary>
        public int ReservedQuantity { get; set; }

        /// <summary>
        /// Minimum stock level for reordering
        /// </summary>
        public int MinimumStockLevel { get; set; }

        /// <summary>
        /// Product category
        /// </summary>
        public string Category { get; set; } = string.Empty;

        /// <summary>
        /// Is product active (can be purchased)
        /// </summary>
        public bool IsActive { get; set; }

        /// <summary>
        /// Is stock level low
        /// </summary>
        public bool IsStockLow { get; set; }

        /// <summary>
        /// Creation timestamp
        /// </summary>
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Last modification timestamp
        /// </summary>
        public DateTime? UpdatedAt { get; set; }
    }

    /// <summary>
    /// DTO for creating a new product
    /// 
    /// Why separate DTO?
    /// - Only required fields
    /// - No ID (generated by server)
    /// - No timestamps (set by server)
    /// - Cleaner API contract
    /// </summary>
    public class CreateProductDto
    {
        /// <summary>
        /// Product name (required)
        /// </summary>
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Product description (optional)
        /// </summary>
        public string Description { get; set; } = string.Empty;

        /// <summary>
        /// Stock Keeping Unit (required, unique)
        /// </summary>
        public string Sku { get; set; } = string.Empty;

        /// <summary>
        /// Selling price (required, > 0)
        /// </summary>
        public decimal Price { get; set; }

        /// <summary>
        /// Cost price (required, >= 0)
        /// </summary>
        public decimal Cost { get; set; }

        /// <summary>
        /// Initial stock quantity (required, >= 0)
        /// </summary>
        public int StockQuantity { get; set; }

        /// <summary>
        /// Minimum stock level for reordering (required, >= 0)
        /// </summary>
        public int MinimumStockLevel { get; set; }

        /// <summary>
        /// Product category (required)
        /// </summary>
        public string Category { get; set; } = string.Empty;
    }

    /// <summary>
    /// DTO for updating a product
    /// 
    /// Why separate DTO?
    /// - Different fields than create
    /// - Includes ID (which product to update)
    /// - Includes RowVersion (optimistic locking)
    /// - Some fields immutable (SKU)
    /// </summary>
    public class UpdateProductDto
    {
        /// <summary>
        /// Product ID (which product to update)
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Product name (can be updated)
        /// </summary>
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Product description (can be updated)
        /// </summary>
        public string Description { get; set; } = string.Empty;

        /// <summary>
        /// Selling price (can be updated)
        /// </summary>
        public decimal Price { get; set; }

        /// <summary>
        /// Cost price (can be updated)
        /// </summary>
        public decimal Cost { get; set; }

        /// <summary>
        /// Minimum stock level (can be updated)
        /// </summary>
        public int MinimumStockLevel { get; set; }

        /// <summary>
        /// Product category (can be updated)
        /// </summary>
        public string Category { get; set; } = string.Empty;

        /// <summary>
        /// Is product active (can be updated)
        /// </summary>
        public bool IsActive { get; set; }

        /// <summary>
        /// Row version for optimistic locking
        /// 
        /// Why?
        /// - Prevents concurrent update conflicts
        /// - If someone else updated, this will be stale
        /// - Database rejects the update
        /// - Client gets error and can retry
        /// </summary>
        public byte[]? RowVersion { get; set; }
    }

    /// <summary>
    /// DTO for stock operations
    /// </summary>
    public class StockOperationDto
    {
        /// <summary>
        /// Product ID
        /// </summary>
        public Guid ProductId { get; set; }

        /// <summary>
        /// Quantity to add/remove
        /// </summary>
        public int Quantity { get; set; }

        /// <summary>
        /// Operation type: "Add", "Remove", "Reserve", "Release", "Confirm"
        /// </summary>
        public string OperationType { get; set; } = string.Empty;
    }
}
