name: Deploy Azure Function App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: orderprocessor-func
  RESOURCE_GROUP_NAME: rg-ecomm-app-dev
  DOTNET_VERSION: "8.0.x"
  FUNCTIONAPP_PROJECT: OrderProcessor.Function/OrderProcessor.Function.csproj

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.FUNCTIONAPP_PROJECT }}

      - name: Build
        run: dotnet build ${{ env.FUNCTIONAPP_PROJECT }} --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ${{ env.FUNCTIONAPP_PROJECT }} --configuration Release --output ./publish

      - name: Zip publish output
        run: |
          cd publish
          zip -r ../functionapp.zip .

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ZIP to Azure Function App
        run: |
          az functionapp deployment source config-zip \
            --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
            --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
            --src functionapp.zip
